version: '2'
services:
  rails: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        DB_URL: db
        DB_USERNAME: root
        DB_PASSWORD: rootpassword
        DB_PORT: 3306
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app"
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  webpack:
    <<: *app_base
    command: ["yarn", "webpack-dev-server"]
    ports:
      - "3035:3035"
    depends_on:
      - rails
    tty: false
    stdin_open: false
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: rails6-vue2-ts3-skeleton
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes_from:
      - data
    ports:
      - "3307:3306"
  data:
    image: "busybox"
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "bundle_install:/app/vendor/bundle"
      - "bundle:/app/.bundle"
      - "node_modules:/app/node_modules"

volumes:
  mysql-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
